### ISSUE TITLE
Unsupported mapnik installation type results in 400 response, rather than 500

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#118]
This error:

```
{"errors":["Could not create datasource for type: 'postgis'  encountered during 
                   parsing of layer 'layer0' in Layer at line 19"]}
```

Is sent to the client with a 400 response. Should be an internal server error instead.
See https://github.com/CartoDB/cartodb/issues/355

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
