### ISSUE TITLE
Malformed torque CartoCSS: Error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft#150]
Using unquoted values for some torque attributes result in a weird error message.
Example unquoted value:

-torque-time-attribute:cartodb_id;

Error:

{"error":"Error: Cannot read property '0' of undefined"}

Needs an automated testcase

\cc @javisantana

**Comment by fdansv** [comment]
At the moment leaving ```-torque-time-attribute``` unquoted causes no problems, while doing the same thing in ```-torque-aggregation-function``` raises an "unexpected identifier" error. So that works as it should.

So far I haven't been able to replicate it raising a "Cannot read property 0 of undefined". This was probably solved at some point since it was reported more than a year ago?

**Comment by strk** [comment]
You can see I added a pending test for the bug with 28a097e816ad3263fcd35fa1090fc1e8b8232272 so maybe you can see if it's now run ("test.skip" is not run, "test" is run). If it is and succeeds this bug can be closed.

**Comment by fdansv** [comment]
Sooo... the thing is despite `-torque-aggregation-function` being a carto `function` type, Windshaft casts all incoming rules to strings by using `Object.prototype.toString`. This works fine for strings and numbers, but not so much for functions, in which case it just returns `[object Object]`.

And this, of course, causes trouble with the SQL query when putting `[object Object]` in there.
