### ISSUE TITLE
Cannot create a working tile server based on documentation.

### ISSUE THREAD

**Issue by lliss** [CartoDB/Windshaft#329]
Following the instructions in the readme, does not result in a working tiler.

Do the docs need to be updated?

**Comment by rochoa** [comment]
Hi @lliss,

Right now in master branch @ https://github.com/CartoDB/Windshaft/commit/ad5c21e7a4cd1e8461e9a78fc9fd9dbe57a3f1f0:

```shell
$ npm install
$ node examples/readme_server.js
map tiles are now being served out of: http://localhost:4000/database/:dbname/layergroup
```

Can you validate it?

**Comment by lliss** [comment]
Yes. The demo server did start.

**Comment by kireniusdena** [comment]
How to fix this 

> `cannot connect to the database

and config readme_server.js`

`var config = {
    base_url: '/database/:dbname/table/:table',
    base_url_mapconfig: '/database/:dbname/layergroup',
    grainstore: {
                 datasource: {user:'postgres', host: '127.0.0.1',password:'bukapeta',database:'aidenvironment', port: 5432}
    }, //see grainstore npm for other options
    redis: {host: '127.0.0.1', port: 6379},
    enable_cors: true,
    req2params: function(req, callback){
        // this is in case you want to test sql parameters eg ...png?sql=select * from my_table limit 10
        req.params =  _.extend({}, req.params);
        _.extend(req.params, req.query);

        // send the finished req object on
        callback(null,req);
    }
};`

**Comment by manueltimita** [comment]
I'm reopening this issue because I think both the documentation and the example need to be updated.

@kireniusdena this is how you can do it. In the given example, somehow the PG username is not passed further from `grainstore.datasource.user`, so you need to change line 28 in `examples/readme_server.js`:

`req.params =  _.extend({}, req.params);` 
to 
`req.params =  _.extend({ dbuser: 'postgres' }, req.params);`

Also, Windshaft uses two custom PG functions, `CDB_QueryTables` and `CDB_QueryStatements`, which you need to install, otherwise you'll get more errors. 

You can find both of them here: https://github.com/CartoDB/cartodb-postgresql/tree/master/scripts-available. For the latter to work, you need to have the extension `plpythonu` installed in PG. If you are using Ubuntu, simply `sudo apt-get install postgresql-plpython` and then in the database that you are using for Windshaft do `CREATE EXTENSION plpythonu`

You then should have no problems running the example server.
