### ISSUE TITLE
Document how to specify the types of layers that will be rendered when fetching tiles

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft#333]
MapConfig 1.3.0 allows multiple types of layers (mapnik, http, etc.).

We need to document how to set [the types of layers that will be rendered when fetching tiles](https://github.com/CartoDB/Windshaft/blob/master/doc/Multilayer-API.md#fetch-tiles).

- `:base_url_mapconfig/:TOKEN/{z}/{x}/{y}.png`
- `:base_url_mapconfig/:TOKEN/all/{z}/{x}/{y}.png`
- ...

**Comment by rochoa** [comment]
Sorry I don't follow you. :turtle:

What do you mean by "how to specify the types"?

**Comment by alonsogarciapablo** [comment]
According to the docs `:base_url_mapconfig/:TOKEN/{z}/{x}/{y}.png` will render **all cartodb/mapnik** layers together in the specified order.

I know that the `/all` parameter in `:base_url_mapconfig/:TOKEN/all/{z}/{x}/{y}.png` will cause the tiler to render **all** layers (not only cartodb/mapnik ones). But this is not documented.

Are there any other options? For example, is it possible to render only `http` layers?

**Comment by rochoa** [comment]
Thanks for the help! Feeling :car: :dash: now!

It's possible but it's not documented because I don't see it as an stable enough API right now.

Check: https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/renderers/renderer_factory.js#L39-L43

@javisantana I think we should prioritize this and make the layer API official and documented, specially now that it's growing and we plan to expose in front-end libraries. What do you think?

**Comment by rochoa** [comment]
This is now documented in https://github.com/CartoDB/Windshaft-cartodb/blob/master/docs/Map-API.md#blending-and-layer-selection
