### ISSUE TITLE
Should cartocss and cartocss_version be required when serving GeoJSON tiles?

### ISSUE THREAD

**Issue by fdansv** [CartoDB/Windshaft#407]
At the moment, as per the mapconfig specification, passing each layer's CartoCSS and CartoCSS version is required. Since GeoJSON [doesn't know about style](https://www.timeshighereducation.com/sites/default/files/styles/the_breaking_news_image_style/public/Pictures/web/g/v/u/mans_feet_in_sandals.jpg?itok=ZSwwX_i3), should we remove this requirement when serving vector tiles?

@rochoa cc @dgaubert

**Comment by rochoa** [comment]
As I agree with you, at the moment we don't use CartoCSS, remember that:
 - We need a fallback mechanism to render server side when frontend is not able to handle the load/cartocss.
 - We might end relying on CartoCSS to filter server side.
 - We might generate CartoCSS for the frontend based on the data.

That's why I would keep CartoCSS as a mandatory option. What do you think @dgaubert?

**Comment by dgaubert** [comment]
This is the kind of things I always want to keep simpler. As seen as CartoCSS will be used, as @rochoa said above, when fallback mechanism will be necessary to render in server side, I'd keep it as mandatory as well.

So, I must say, I've also tempted to remove CartoCSS as mandatory option.

**Comment by fdansv** [comment]
Cool, let's keep it this way. d3.cartodb will be sending the styles already provided by the client/config.
