### ISSUE TITLE
histogram returns bad data when setting start and end parameters

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/Windshaft#634]
When calling the histogram URL for a numeric column with `start` and `end` parameters, the endpoint returns bad data for the buckets in the extremes.

**NO START**

```json
{
	"bin_width": 46.6666666666667,
	"bins_count": 3,
	"bins_start": 9,
	"bins": [{
		"bin": 0,
		"min": 9,
		"max": 55,
		"avg": 35.405126849894295,
		"freq": 3784
	}, {
		"bin": 1,
		"min": 56,
		"max": 102,
		"avg": 75.28977482465855,
		"freq": 2709
	}, {
		"bin": 2,
		"min": 103,
		"max": 149,
		"avg": 123.25338491295938,
		"freq": 517
	}],
	"type": "histogram"
}
```

We can see that this histogram has a range from 9 to 149.

If we set `start: 50` and `end: 100` we get

```json
{
	"bin_width": 16.6666666666667,
	"bins_count": 3,
	"bins_start": 50,
	"bins": [{
		"bin": 0,
		"min": 9,
		"max": 66,
		"avg": 40.28936078936079,
		"freq": 4662
	}, {
		"bin": 1,
		"min": 67,
		"max": 83,
		"avg": 74.27996254681648,
		"freq": 1068
	}, {
		"bin": 2,
		"min": 84,
		"max": 149,
		"avg": 105.07421875,
		"freq": 1280
	}],
	"type": "histogram"
}
```

We can see that the buckets are 3, starting at 50 with a width of 16.67. So they are

```
|------|------|------|
50   66.7   83.4    100
```
This is correct. We asked for data between 50 and 100 so these are the proper buckets.

BUT if we study the bins data we get:
Bin 0: min 9, max 66 (min should be above 50)
Bin 1: min 67, max 83 (this is ok)
Bin 2: min 84, max 149 (max should be below 100)

**Comment by Algunenano** [comment]
Yeah, in a quick look I can see that the query (`__cdb_filtered_source`) lacks a `WHERE column > min AND WHERE column < max`  when the parameters are passed.

cc/ @CartoDB/rt-managers

**Comment by ivanmalagon** [comment]
It should be `>= ` and `<=`, right?

If I need to check prices between 50 and 150 I want that numbers to be included.

**Comment by rafatower** [comment]
I'm working on this [branch](https://github.com/CartoDB/Windshaft-cartodb/compare/fix-numeric-histogram-bounds?expand=1) in Windshaft-cartodb repo.

**Comment by rafatower** [comment]
Hey there, Ivan et al. I noticed the parameters `start` and `end` are not documented https://github.com/CartoDB/Windshaft-cartodb/blob/master/docs/MapConfig-Dataviews-extension.md#histograms and they are used in some funny ways. E.g: as per the code, the max and min are calculated when you pass `start >= end`.

So, there's a lack of definition of what to do, for instance, if `start` is defined and `end` is not, or the other way around. Not hard to define but... mentioning it because touching histograms is not straightforward, at least without causing regressions or impacting performance.

So, personally I'd fix this particular issue and leave the case "`start` is defined and `end` is not" out of the equation, unless you tell me this is a must for you now.

**Comment by Algunenano** [comment]
> E.g: as per the code, the max and min are calculated when you pass start >= end.

That specific case is handled in the base view so they [will be flipped](https://github.com/CartoDB/Windshaft-cartodb/blob/c1671abaa49c46ed1544f05125afeb4691321ac8/lib/cartodb/models/dataview/histograms/base-histogram.js#L66) before getting there, but it's true that unexpected things will happen if you only pass one of them.
