### ISSUE TITLE
Move client parameter to header

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/Windshaft#635]
Feature request:

We are adding a `client` parameter to map instantiation to know who is doing that instantiation.
CARTO VL: `map?client=vl-0.9.2`
CARTO.js: `map?js=js-4.0.9`

This implies that everytime we publish a new version, the cache invalidates.

As @dgaubert suggested, we should move this to a request header, to be able to gather metrics about who our users are and respect the map cache.

**Comment by rochoa** [comment]
How is this related to the backend? I mean, that's something the client sends.

OTHO, versions don't change that often and when they do, it's not so critical to not have a cached response. Especially considering that:
- In CARTO VL all map instantiations are using POST requests.
- The performance is gonna be worse because of the new bundle for the library than for going to the backend again.

**Comment by rochoa** [comment]
BTW, this will also require changes to push that new header to the logs to be able to consume it from different metrics components.

**Comment by rochoa** [comment]
I actually don't understand what is proposed in this issue.

**Comment by enekid** [comment]
_Frontenders_ want to send a `parameter` in order to monitor `carto.js` vs `carto VL` usage

If they put this parameter in the query string it affects caching. Their proposal is to send this parameter in a `http header` (eg. `X-Client`). APIs should read this `http header` and add it's content to the logs.

Right now, the log format is:

`,log_format: ':req[X-Real-IP] :method :req[Host]:url :status :response-time ms -> :res[Content-Type] (:res[X-Tiler-Profiler])'`

With the client parameter it would look something like (TBD):

`,log_format: ':req[X-Real-IP] :method :req[Host]:url :status :response-time ms -> :res[Content-Type] (:res[X-Tiler-Profiler]) :req[X-Client]'`

**Comment by ivanmalagon** [comment]
We are adding the client parameter to the map instantiation in CARTO.js public API. When we talked to @dgaubert he told us just to be aware of the cache invalidation everytime we published a new version and he suggested to include it in a header instead of a parameter to avoid this.

It's not urgent but I opened the issue to not forget about it. Backend needs to do some changes to consume the metrics from the header, I guess. In the meantime we're continuing to send it as a parameter (it's not a big deal as you say).

**Comment by rochoa** [comment]
More reasons to not do this:
1. If we don't change every layer to be aware of the header, we won't be able to get the header with the version at the application layer. That means that any intermediate layer (CDN, nginx, varnish) should be aware of that header in order to let it pass. That means adding new functionality to handle the header in all the layers between the browser/client and the application server.
1. If you have to do that, you will be hitting the application layer again. So all the effort to not use a query parameter in the URL will vanish because you have to hit the application layer to be able to log that header. Something you got for granted by just simply using the query parameter.
1. Even more, with the new header, you won't be able to cache anymore any request because you have to let pass all of them to log them at the application layer.

**Comment by dgaubert** [comment]
You are right. This is a clear `Won't fix`. 

Closing then.
